### ISSUE TITLE
Add support for 2e icon roll rules

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/13th-age#145]
In GitLab by @Asacolips on Dec 19, 2022, 09:38

## Summary

In !259 we added support for the 13th Age 2e playtest to the system, but we did not add support for the new icon roll rules. The new rules are a fairly significant departure from the previous rules, so we'll need to experiment a bit with the UX design for it and come up with a better solution to handle them.

## Notes

The new rules are:

1. At the start of a day (meaning once per full heal-up) roll a d6 for each icon relationship.
2. Highest die result (or results, if a tie) will give you an icon connection that can be used later in the session.
3. When you use a connection, roll a d6. On a 3+, there are no serious complications. On a 1-2, the GM decides a complication.
4. Icon connections are lost at the end of the day/heal-up.

## Labels

/cc @Asacolips @cswendrowski @LegoFed3

**Comment by LegoFed3** [comment]
No longer needed as of the beta packet, closing.
