### ISSUE TITLE
[BUG] Dragging PC power to hotbar only works in a very specific state

### ISSUE THREAD

**Issue by ben** [asacolips-projects/13th-age#433]
### Describe the bug
Dragging PC powers into the macro hotbar only works if the sort is set to "custom" when the sheet opens.

(It's not the core issue here, but only being able to drag things when the sort is "custom" is confusing for players, there's no indication as to why some characters can drag and others can't. It could be that the simplest solution is to just turn on `draggable` and `data-draggable` in all sort modes.)

### To Reproduce
1. Set a PC's power sorting to "level"
2. Close the sheet and reopen it
3. Set the sorting to "custom" to enable dragging
4. Try to drag a power to the macro bar, and see nothing happen
5. Close the sheet and reopen
6. Drag power to hotbar, and it works

#### Expected behavior
This should create a macro that triggers the power.

### Screenshots
Here's a video showing the behavior with a commander (sort set to custom when sheet was open) and an occultist (sort was set to level, then changed to "custom" without closing the sheet)

https://github.com/asacolips-projects/13th-age/assets/39902/108c8923-c334-4d4d-a1c1-2bda05140c62

### Desktop
 - OS: Mac
 - Browser Chrome
 - Foundry Version 11.315
 - System Version 1.29.2

**Comment by LegoFed3** [comment]
This *should* be fixed in 1.31.0

**Comment by asacolips** [comment]
Yep, I overhauled both the drag handling and macro creation in 1.31.0, so this can be closed.
