### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Maleketh** [asacolips-projects/13th-age#454]
**Describe the bug**
I've noticed a few more bugs in the system, at least in V12.  The specifically relate to using the automated "Apply as damage."  When a player character does it, the damage is applied incorrectly, typically immediately reducing them to critical or negative HP values.  According to a player who experimented with it, it seems to be reducing the character's HP to a fixed amount before applying the damage, but the fixed amount is different from character to character.  Doing this doesn't automatically apply Staggered or Dead, but does lower the character's base AC by 1.

When the damage is applied to a monster, it's applied correctly, but there's no damage popup over the token, and the Staggered/Dead conditions aren't applied correctly.

**To Reproduce**
1. Start a game and roll a damage value.
2. Select a token, right-click the damage value, and choose "Apply as damage."

**Expected behavior**
Damage should be applied correctly, with damage messages and Staggered/Dead applied automatically.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: GM runs in Foundry directly; players use a mix of Firefox & Chrome
 - Foundry Version: 12
 - System Version: 1.30.3

**Comment by LegoFed3** [comment]
Fixed in 1.30.4.
